### ISSUE TITLE
Force player to use audio UI

### ISSUE THREAD

**Issue by hemb** [googlecast/BasicReceiverCAF#3]
I have a HLS audio stream (mp3) that I want to cast, but the CAF player is using the video UI (just showing a blank screen while playing). Is it possible to force the player to use the audio UI?

The codec in the HLS manifest is mp4a.40.34, but since Chromecast doesn't support it I process the manifest and change the codec to mp4a.69 (mp4a.6B also works):
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=47774,CODECS="mp4a.69"
https://host.com/libraryTS/v4/mp3:http/f747dd19&validate=3f379
```

The MEDIA_STATUS message shows `"tracks":[{"trackId":1,"trackContentType":"video/mp2t","type":"VIDEO"}]}` and I have tried to change it to `"tracks":[{"trackId":1,"trackContentType":"audio/mp3","type":"AUDIO"}]}` without any luck.

Here's what the playlist looks like:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="https://host.com/libraryTS/v4/mp3:http/f747dd19.mp3/key_w143.m3u8key?wowzasessionid=1439&StreamSession=c7b1726f&validate=3f379"
#EXTINF:10.0,
https://host.com/libraryTS/v4/mp3:http/f747dd19.mp3/media_w143_0.ts?StreamSession=c7b1726f&validate=3f379
```

**Comment by entertailion** [comment]
You can file a feature request for the Cast SDK: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc
