### ISSUE TITLE
How to set Cors header in CAF receiver

### ISSUE THREAD

**Issue by rangav** [googlecast/BasicReceiverCAF#5]
Hi 

When i try to play youtube video with Custom Receiver i am getting CORS header issue.

How i can set CORS header in CAF receiver , can't find any code sample?

Thanks

**Comment by entertailion** [comment]
CORS should be configured on your server hosting the media content: https://developers.google.com/cast/docs/player#cors

**Comment by rangav** [comment]
But i am trying to cast youtube video https://youtu.be/eACohWVwTOc from iphone app to chromecast, not the hosted content.

How can set CORS in CAF receiver in this case?

**Comment by entertailion** [comment]
Thats not how CORS works. It is the server hosting the media content that configures the CORS header, in this case YouTube.

**Comment by rangav** [comment]
I am able to play youtube video on styled media player, but cannot play the same video on custom receiver? 

is there any workaround for this?

**Comment by entertailion** [comment]
You will have to check with YouTube if they support your use case. Typically YouTube expects users to use the YouTube app to cast videos.
