### ISSUE TITLE
Using the latest CAF SDK my chromecast receiver disconnect after 5 minutes

### ISSUE THREAD

**Issue by xdemocle** [googlecast/BasicReceiverCAF#7]
Hi, is there a way to avoid closing my chromecast receiver app after 5 minutes?
I tried setting the maxInactivity and other 2 thousands work around but with no luck.

With older SDK my web page working as Receiver on chromecast was working well, but after updating to CAF SDK it keeps disconnecting and closing.

Any solutions? Please do the magic, it's few days i'm trying to solve this, the last solution is going back to SDK v2. Thanks

**Comment by entertailion** [comment]
The CAF SDK implements the Cast best practices: "Disconnect from the receiver app and stop it from running if idle for 5 minutes (or less)."
https://developers.google.com/cast/docs/design_checklist/receiver#receiver-ui-idle

**Comment by xdemocle** [comment]
Thanks @entertailion  for prompt reply. Is there any way to avoid it? Because i'm actually using the chromecast for showing a web interface as dashboard piloted from the sender thanks to the session sendMessage in background. It's not an official app for html5 streaming and using only the basic CAF features. Btw, i'm not developing a large scale app but only a simple cast button on my webtool that connects to the chromecast and interact remotely with the web interface.

**Comment by entertailion** [comment]
There might be a way to send custom messages from the receiver to the sender. Alternatively, you could play media (maybe silent) in the background in some kind of endless queue.

(I was born in Cape Town)
