### ISSUE TITLE
How to display image as adbreak with duration in CAF receiver?

### ISSUE THREAD

**Issue by samsol38** [googlecast/BasicReceiverCAF#8]
How to display image as adbreak with duration in CAF receiver?
https://developers.google.com/cast/docs/caf_receiver_features?authuser=1#ad-breaks

I passed image url in contentId with duration. But it display image with pause status. After completion of duration, Video is not continued.

Please reply me asap.

**Comment by entertailion** [comment]
Add breaks are meant to be video clips. You can convert your images to videos or you can file a feature request: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc
